{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}-config
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
  {{- include "labels.common" . | nindent 4 }}
data:
  tbot.yaml: |
    version: v2
    onboarding:
      join_method: kubernetes
      # ensure token is set to the name of the join token you created earlier
      token: bot-{{ .Values.teleport.tokenName }}
    renewal_interval: {{ .Values.renewal_interval }}
    certificate_ttl: {{ .Values.certificate_ttl }}
    storage:
      # a memory destination is used for the bots own state since the kubernetes
      # join method does not require persistence.
      type: memory
    # ensure this is configured to the address of your Teleport Proxy or
    # Auth Server. Prefer the address of the Teleport Proxy.
    proxy_server: {{ .Values.teleport.proxyAddr }}
    # outputs will be filled in during the completion of an access guide.
    {{- if or (.Values.defaultOutput.enabled) (.Values.outputs) }}
    outputs:
    {{- if .Values.defaultOutput.enabled }}
    - type: identity
      destination:
        type: kubernetes_secret
        name: {{ .Values.defaultOutput.secretName }}
    {{- end }}
    {{- end }}
    {{- if .Values.outputs }}
    {{- range $key, $value := .Values.outputs }}
    - type: kubernetes
      kubernetes_cluster: {{ $key }}
      disable_exec_plugin: true
      destination:
        type: kubernetes_secret
        name: teleport-{{ $value }}-kubeconfig
    {{- end }}
    {{- end }}
      - type: identity
        destination:
          type: kubernetes_secret
          name: teleport-identity-output
{{- end }}
