version: 2.1

orbs:
  architect: giantswarm/architect@5.0.1

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: teleport-tbot
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite" # uncomment this if you want automatic metadata generation and helm chart linting
          name: push-teleport-tbot-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "teleport-tbot"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capa-app-collection
          app_name: "teleport-tbot"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-teleport-tbot-to-app-catalog
            - push-to-registries
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-cloud-director-app-collection
          app_name: "teleport-tbot"
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - push-teleport-tbot-to-app-catalog
            - push-to-registries
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-capz-app-collection
          app_name: "teleport-tbot"
          app_collection_repo: "capz-app-collection"
          requires:
            - push-teleport-tbot-to-app-catalog
            - push-to-registries
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-gcp-app-collection
          app_name: "teleport-tbot"
          app_collection_repo: "gcp-app-collection"
          requires:
            - push-teleport-tbot-to-app-catalog
            - push-to-registries
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-vsphere-app-collection
          app_name: "teleport-tbot"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-teleport-tbot-to-app-catalog
            - push-to-registries
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
