version: 2.1

orbs:
  architect: giantswarm/architect@5.15.0

workflows:
  version: 2
  build:
    jobs:
    - architect/push-to-app-catalog:
        name: push-to-giantswarm-app-catalog
        context: architect
        executor: app-build-suite
        app_catalog: giantswarm-catalog
        app_catalog_test: giantswarm-test-catalog
        chart: teleport-tbot
        filters:
            # Trigger the job also on git tag.
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        context: architect
        executor: app-build-suite
        name: package and push chart to control-plane-catalogs
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: teleport-tbot
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-collection:
        context: architect
        name: capz-app-collection
        app_name: teleport-tbot
        app_namespace: giantswarm
        app_collection_repo: capz-app-collection
        requires:
        - package and push chart to control-plane-catalogs
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
    - architect/push-to-app-collection:
        context: architect
        name: capa-app-collection
        app_name: teleport-tbot
        app_namespace: giantswarm
        app_collection_repo: capa-app-collection
        requires:
        - package and push chart to control-plane-catalogs
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
    - architect/push-to-app-collection:
        context: architect
        name: vsphere-app-collection
        app_name: teleport-tbot
        app_namespace: giantswarm
        app_collection_repo: vsphere-app-collection
        requires:
        - package and push chart to control-plane-catalogs
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
    - architect/push-to-app-collection:
        context: architect
        name: cloud-director-app-collection
        app_name: teleport-tbot
        app_namespace: giantswarm
        app_collection_repo: cloud-director-app-collection
        requires:
        - package and push chart to control-plane-catalogs
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^v.*/
