version: 2.1

orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-default-app-catalog
          context: architect
          executor: app-build-suite
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "teleport-tbot"
          persist_chart_archive: true
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-giantswarm-app-catalog
          context: architect
          executor: app-build-suite
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "teleport-tbot"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-teleport-tbot-app-to-control-plane-app-catalog
          context: architect
          executor: app-build-suite
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "teleport-tbot"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      # deploy to aws installations (only tags)
      - architect/push-to-app-collection:
          name: push-teleport-tbot-app-to-aws-app-collection
          context: architect
          app_name: "teleport-tbot-app"
          app_namespace: "kube-system"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-teleport-tbot-app-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to azure installations (only tags)
      - architect/push-to-app-collection:
          name: push-teleport-tbot-app-to-azure-app-collection
          context: architect
          app_name: "teleport-tbot-app"
          app_namespace: "kube-system"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-teleport-tbot-app-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            branches:
              ignore:
                - main
          requires:
            - push-to-giantswarm-catalog