version: 2.1

orbs:
  architect: giantswarm/architect@5.2.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-giantswarm-app-catalog
          context: architect
          executor: app-build-suite
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "teleport-tbot"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
